package com.gdcontrol.desktop.visao.consulta;

import com.gdcontrol.desktop.controle.consulta.ControleConsultaPosologia;
import com.gdcontrol.desktop.controle.manutencao.ControleManutencaoPosologia;
import com.gdcontrol.desktop.util.tablemodel.PosologiaTableModel;
import com.gdcontrol.desktop.visao.manutencao.VisaoManutencaoPosologia;
import com.gdcontrol.entidade.Posologia;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author gustavo
 */
public class VisaoConsultaPosologia extends VisaoConsultaPadrao {

    public static final String OPCAO_ID = "ID";
    public static final String OPCAO_DOSAGEM = "Dosagem";
    public static final String OPCAO_HORA = "Hora";
    public static final String OPCAO_INICIO_PRESCRICAO = "Início Prescrição";
    public static final String OPCAO_FINAL_PRESCRICAO = "Final Prescrição";
    
    /**
     * Creates new form VisaoConsultaPosologia
     */
    public VisaoConsultaPosologia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregaPosologias();
        getOpcoesPesquisa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbCampoPesquisa = new javax.swing.JComboBox();
        edPesquisa = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPosologia = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Posologia");

        jLabel1.setText("Campo Pesquisa:");

        jLabel2.setText("Pesquisa:");

        edPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edPesquisaKeyPressed(evt);
            }
        });

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        tbPosologia.setModel(tableModelPosologia);
        tbPosologia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPosologiaMouseClicked(evt);
            }
        });
        tbPosologia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbPosologiaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbPosologia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cbCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btPesquisar))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNovo)
                    .addComponent(btAlterar)
                    .addComponent(btExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        if (!edPesquisa.getText().isEmpty()) {
            tableModelPosologia.limpar();
            String pesquisa = (String) cbCampoPesquisa.getSelectedItem();
            switch (pesquisa) {
                case OPCAO_ID:
                    try {
                        filtraId(Integer.parseInt(edPesquisa.getText()));
                    } catch (NumberFormatException e) {
                    }
                    break;
                case OPCAO_DOSAGEM:
                    filtraDosagem(edPesquisa.getText());
                    break;
                case OPCAO_HORA:
                    filtraHora(edPesquisa.getText());
                    break;
                case OPCAO_INICIO_PRESCRICAO:
                    filtraInicioPrescricao(edPesquisa.getText());
                    break;
                case OPCAO_FINAL_PRESCRICAO:
                    filtraFinalPrescricao(edPesquisa.getText());
                    break;
            }
            tableModelPosologia.fireTableDataChanged();
        } else {
            carregaPosologias();
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void edPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edPesquisaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btPesquisarActionPerformed(null);
        }
    }//GEN-LAST:event_edPesquisaKeyPressed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        VisaoManutencaoPosologia manutencao = new VisaoManutencaoPosologia(null, true);
        manutencao.setVisible(true);
        carregaPosologias();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        int indice = tbPosologia.getSelectedRow();
        if (indice >= 0) {
            VisaoManutencaoPosologia manutencao = new VisaoManutencaoPosologia(null, true);
            ControleManutencaoPosologia controleManutencao = (ControleManutencaoPosologia) manutencao.getControle();
            controleManutencao.setModelo(tableModelPosologia.getPosologia(indice));
            controleManutencao.setTela(manutencao);
            controleManutencao.carregaTela();
            manutencao.setVisible(true);
            carregaPosologias();
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void tbPosologiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbPosologiaKeyPressed
        
    }//GEN-LAST:event_tbPosologiaKeyPressed

    private void tbPosologiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPosologiaMouseClicked
        if (evt.getClickCount() == 2) {
            btAlterarActionPerformed(null);
        }
    }//GEN-LAST:event_tbPosologiaMouseClicked

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int indice = tbPosologia.getSelectedRow();
        if (indice >= 0) {
            int opcao = JOptionPane.showConfirmDialog(this, "Confirma exclusão da Posologia selecionada?");
            if(opcao == JOptionPane.YES_OPTION){
                getControle().excluir(tableModelPosologia.getPosologia(indice));
                carregaPosologias();
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisaoConsultaPosologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisaoConsultaPosologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisaoConsultaPosologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisaoConsultaPosologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VisaoConsultaPosologia dialog = new VisaoConsultaPosologia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JComboBox cbCampoPesquisa;
    private javax.swing.JTextField edPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPosologia;
    // End of variables declaration//GEN-END:variables

    ControleConsultaPosologia controle = new ControleConsultaPosologia();
    PosologiaTableModel tableModelPosologia = new PosologiaTableModel();
    
    @Override
    public void getOpcoesPesquisa() {
        Vector comboBoxItems = new Vector();
        comboBoxItems.add(OPCAO_ID);
        comboBoxItems.add(OPCAO_DOSAGEM);
        comboBoxItems.add(OPCAO_HORA);
        comboBoxItems.add(OPCAO_INICIO_PRESCRICAO);
        comboBoxItems.add(OPCAO_FINAL_PRESCRICAO);
        final DefaultComboBoxModel model = new DefaultComboBoxModel(comboBoxItems);
        this.cbCampoPesquisa.setModel(model);
    }
    
    private void carregaPosologias(){
        tableModelPosologia.limpar();
        for (Posologia pos : (List<Posologia>) getControle().listar()) {
            tableModelPosologia.addPosologia(pos);
        }
        tableModelPosologia.fireTableDataChanged();
    }
    
    private void filtraId(int id) {
        Posologia pos = getControle().filtraId(id);
        if(pos != null){
            tableModelPosologia.addPosologia(pos);
        }
    }

    private void filtraDosagem(String dosagem) {
        for (Posologia pos : (List<Posologia>) getControle().filtraDosagem(dosagem)) {
            tableModelPosologia.addPosologia(pos);
        }
    }
    
    private void filtraHora(String hora) {
        for (Posologia pos : (List<Posologia>) getControle().filtraHora(hora)) {
            tableModelPosologia.addPosologia(pos);
        }
    }
    
    private void filtraInicioPrescricao(String data) {
        for (Posologia pos : (List<Posologia>) getControle().filtraInicioPrescricao(data)) {
            tableModelPosologia.addPosologia(pos);
        }
    }
    
    private void filtraFinalPrescricao(String data) {
        for (Posologia pos : (List<Posologia>) getControle().filtraFinalPrescricao(data)) {
            tableModelPosologia.addPosologia(pos);
        }
    }

    @Override
    public ControleConsultaPosologia getControle() {
        return this.controle;
    }
}
